### ISSUE TITLE
Prepare-Step fails with setuptools 70

### ISSUE THREAD

**Issue by 0xC0DEBA5E** [abichinger/semantic-release-pypi#37]
It seems like setuptools 70.0.0 has removed the deprecated `pkg_resources` API which is used by the prepare step of this library.

Here is an excempt from the logs of the CI-Pipeline of our application:

```
[8:07:34 AM] [semantic-release] › ✖  Failed step "prepare" of plugin "semantic-release-pypi"
[8:07:34 AM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Command failed with exit code 1: python -c import pkg_resources
print(pkg_resources.packaging.version.Version('5.3.0'))
<string>:1: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
Traceback (most recent call last):
  File "<string>", line 2, in <module>
AttributeError: module 'pkg_resources' has no attribute 'packaging'
    at makeError (/builds/distel-digital/entwicklung/eventtypes/node_modules/semantic-release-pypi/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/builds/distel-digital/entwicklung/eventtypes/node_modules/semantic-release-pypi/node_modules/execa/index.js:114:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async normalizeVersion (/builds/distel-digital/entwicklung/eventtypes/node_modules/semantic-release-pypi/lib/util.js:10:24)
    at async prepare (/builds/distel-digital/entwicklung/eventtypes/node_modules/semantic-release-pypi/lib/prepare.js:44:19)
    at async validator (/builds/distel-digital/entwicklung/eventtypes/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
    at async /builds/distel-digital/entwicklung/eventtypes/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
    at async Promise.all (index 0)
    at async next (/builds/distel-digital/entwicklung/eventtypes/node_modules/p-reduce/index.js:16:18) {
  shortMessage: 'Command failed with exit code 1: python -c import pkg_resources\n' +
    "print(pkg_resources.packaging.version.Version('5.3.0'))",
  command: 'python -c import pkg_resources\n' +
    "print(pkg_resources.packaging.version.Version('5.3.0'))",
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '<string>:1: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html\n' +
    'Traceback (most recent call last):\n' +
    '  File "<string>", line 2, in <module>\n' +
    "AttributeError: module 'pkg_resources' has no attribute 'packaging'",
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  pluginName: 'semantic-release-pypi'
}
```

Our Workaround:
After a downgrade of setuptools from 70.0.0 to 69.5.1 everything worked again.

Solution:
I think in the long term upgrading to an alternative API as described in https://setuptools.pypa.io/en/latest/pkg_resources.html would be a solution.

**Comment by abichinger** [comment]
Thanks!

The plugin now uses [`packaging`](https://pypi.org/project/packaging/) instead of `pkg_resources.packaging`.
