### ISSUE TITLE
Getting an error with lodash import after latest commit

### ISSUE THREAD

**Issue by ignacio-kognitos** [abichinger/semantic-release-pypi#41]
After latest changes I have failing pipelines because of an unresolved import.

This seems to be the conflicting change https://github.com/abichinger/semantic-release-pypi/commit/c0d4031286a173191c6a8324b5e62e0792dc13ec#diff-f4ab32fb5c8616320ebab8137b8ae26da659a4cfc2201832680090056d2c8e9cR3

```
[3:38:07 PM] [semantic-release] › ℹ  Running semantic-release version 24.2.0
[3:38:07 PM] [semantic-release] › ✘  An error occurred while running semantic-release: file:///home/runner/work/_actions/cycjimmy/semantic-release-action/v4/node_modules/semantic-release-pypi/dist/prepare.js:11
import { template } from 'lodash';
         ^^^^^^^^
SyntaxError: Named export 'template' not found. The requested module 'lodash' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'lodash';
const { template } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:146:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:229:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:473:24)
    at async loadPlugin (file:///home/runner/work/_actions/cycjimmy/semantic-release-action/v4/node_modules/semantic-release/lib/plugins/utils.js:60:54)
    at async file:///home/runner/work/_actions/cycjimmy/semantic-release-action/v4/node_modules/semantic-release/lib/plugins/index.js:18:37
    at async default (file:///home/runner/work/_actions/cycjimmy/semantic-release-action/v4/node_modules/semantic-release/lib/plugins/index.js:14:7)
    at async default (file:///home/runner/work/_actions/cycjimmy/semantic-release-action/v4/node_modules/semantic-release/lib/get-config.js:92:30)
    at async Module.default (file:///home/runner/work/_actions/cycjimmy/semantic-release-action/v4/node_modules/semantic-release/index.js:274:34)
    at async release (/home/runner/work/_actions/cycjimmy/semantic-release-action/v4/src/index.js:31:18)
 ```

**Comment by abichinger** [comment]
Thanks! :+1:

**Comment by abichinger** [comment]
Should be fixed

**Comment by ignacio-kognitos** [comment]
> Should be fixed

It works now, thank you for the quick turnaround! @abichinger
